---
- name: symlink net.lo to net.eth0
  file:
    src: /etc/init.d/net.lo
    dest: /etc/init.d/net.eth0
    state: link
- name: ensure net.eth0 starts on boot
  shell: rc-update add net.eth0 default
- name: set root password to vagrant
  user:
    name: root
    password: vagrant
    update_password: always
- name: install gentoolkit
  shell: emerge gentoolkit
- name: set profile
  shell: "eselect profile set {{ gentoo_profile }}"
- name: rebuild system
  portage:
    package: '@world'
    update: yes
    deep: yes
    newuse: yes
#- name: rebuild system
#  shell: "{{ item }}"
#  with_items:
#    - "eselect profile set {{ gentoo_profile }}"
#    - "emerge --update --deep --newuse @world"
- name: set up tzdata
  shell: emerge --config sys-libs/timezone-data
- name: generate locales
  shell: locale-gen && eselect locale set en_US.utf8 && env-update
- name: install genkernel and gentoo-sources
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - gentoo-sources
    - sys-kernel/genkernel
- name: run genkernel
  shell: genkernel all
- name: install net-misc/dhcpcd
  portage:
    package: net-misc/dhcpcd
    state: present
- name: install grub2
  portage:
    package: sys-boot/grub:2
    state: present
- name: setup grub
  shell: "{{ item }}"
  with_items:
    - "grub-install /dev/sda"
    - "grub-mkconfig -o /boot/grub/grub.cfg"
