---
- name: partition /dev/sda
  parted:
    device: /dev/sda
    flags: [ boot ]
    number: 1
    state: present
- name: format /dev/sda1
  filesystem:
    dev: /dev/sda1
    fstype: ext4
- name: mount /dev/sda1 to /mnt/gentoo
  mount:
    path: /mnt/gentoo
    src: /dev/sda1
    fstype: ext4
    state: mounted
