---
- name: ensure tmp folder exists
  file:
    path: /mnt/gentoo/tmp
    state: directory
- name: copy VBoxGuestAdditions.iso to chroot
  shell: cp /root/VBoxGuestAdditions.iso /mnt/gentoo/root/VBoxGuestAdditions.iso
- name: get stage3 tarball
  get_url:
    url: "{{ gentoo_stage3_url }}"
    dest: "/mnt/gentoo/{{ gentoo_stage3_url | basename }}"
    tmp_dest: "/mnt/gentoo/tmp"
    checksum: "sha512:{{ gentoo_latest_stage3_sha512sum }}"
- name: extract stage3 tarball to /mnt/gentoo
  unarchive:
    src: "/mnt/gentoo/{{ gentoo_stage3_url | basename }}"
    dest: "/mnt/gentoo/"
    remote_src: yes
    extra_opts:
      - "--xattrs"
      - "--numeric-owner"
- name: write /mnt/gentoo/etc/fstab
  template:
    src: fstab.j2
    dest: /mnt/gentoo/etc/fstab
- name: write /mnt/gentoo/etc/timezone
  template:
    src: timezone.j2
    dest: /mnt/gentoo/etc/timezone
- name: write /mnt/gentoo/etc/locale.gn
  template:
    src: locale.gen.j2
    dest: /mnt/gentoo/etc/locale.gen
- name: write /etc/conf.d/hostname
  template:
    src: hostname.j2
    dest: /mnt/gentoo/etc/conf.d/hostname
- name: write /etc/conf.d/net
  template:
    src: net.j2
    dest: /mnt/gentoo/etc/conf.d/net
- name: write /etc/hosts
  template:
    src: hosts.j2
    dest: /mnt/gentoo/etc/hosts
- name: write /mnt/gentoo/etc/portage/make.conf
  template:
    src: make.conf.j2
    dest: /mnt/gentoo/etc/portage/make.conf
    follow: yes
- name: create /mnt/gentoo/etc/portage/repos.conf/
  file:
    path: /mnt/gentoo/etc/portage/repos.conf
    state: directory
- name: copy repos.conf
  copy:
    src: /mnt/gentoo/usr/share/portage/config/repos.conf
    dest: /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
- name: copy resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /mnt/gentoo/etc/resolv.conf
- name: set up mounts for install
  shell: "{{ item }}"
  with_items:
    - mount --types proc /proc /mnt/gentoo/proc
    - mount --rbind /sys /mnt/gentoo/sys
    - mount --make-rslave /mnt/gentoo/sys
    - mount --rbind /dev /mnt/gentoo/dev
    - mount --make-rslave /mnt/gentoo/dev
