---
#gentoo_mirror: "http://www.gtlib.gatech.edu/pub/gentoo"
gentoo_mirror: "http://gentoo.osuosl.org"
gentoo_latest_stage3_url: "{{ gentoo_mirror }}/releases/amd64/autobuilds/latest-stage3-amd64.txt"
gentoo_latest_stage3: "{{ lookup('url', gentoo_latest_stage3_url ) | regex_replace('.*,(.*) .*', '\\1') }}"
gentoo_stage3_url: "{{ gentoo_mirror }}/releases/amd64/autobuilds/{{ gentoo_latest_stage3 }}"
gentoo_stage3_digests_url: "{{ gentoo_stage3_url }}.DIGESTS"
#gentoo_latest_stage3_sha512sum: "{{ lookup('url', gentoo_stage3_digests_url) | regex_replace('^# SHA512 HASH,(.*)  .*WHIRL.*SHA512.*WHIRL.*', '\\1') }}"
# this is less messy than my regex approach
# split lookup('url') output on commas, take the 2nd entry, split on spaces. first element in that list is our checksum
gentoo_latest_stage3_sha512sum: "{{ lookup('url', gentoo_stage3_digests_url).split(',').1.split(' ').0 }}"
gentoo_cflags: "-O2 -pipe"
gentoo_portdir: "/usr/portage"
gentoo_distdir: "/usr/portage/distfiles"
gentoo_pkgdir: "/usr/portage/packages"
gentoo_python_targets: "python3_5"
#gentoo_mirrors: "rsync://rsync.gtlib.gatech.edu/pub/gentoo" rsync mirror doesn't seem to be working
#gentoo_mirrors: "http://www.gtlib.gatech.edu/pub/gentoo"
gentoo_mirrors: "http://gentoo.osuosl.org"
gentoo_useflags: "-gtk -gnome -qt4 -qt5 -kde -X -nls -openmp -ipv6 -fortran -sslv3"
gentoo_features: "buildpkg"
gentoo_emerge_default_opts: "${EMERGE_DEFAULT_OPTS} --usepkg --buildpkg-exclude 'virtual/* sys-kernel/*-sources *-bin'"
gentoo_hostname: "vagrant"
gentoo_timezone: "CST6CDT"
gentoo_root_disk: "/dev/{{ 'vda' if packer_build_name == 'qemu' else 'sda' }}"
gentoo_package_use_system:
  - "sys-apps/util-linux static-libs"
  - "dev-vcs/git -iconv -nls -pcre -pcre-jit -perl -webdav -python"
  - "sys-kernel/genkernel -firmware"
  - "app-editors/vim minimal"
  - "sys-boot/grub -fonts -themes"
  - "app-admin/sudo -sendmail"
  - "app-crypt/gnupg -smartcard"
  - "sys-apps/portage -rsync-verify"
gentoo_package_mask_system:
  - ">=sys-devel/gcc-8.0.0"
  - ">=sys-libs/glibc-2.28"
  - ">=dev-lang/python-3.6"
  - "virtual/jdk:1.7"
  - "virtual/jre:1.7"
  - "dev-db/mysql"
  - "dev-db/mariadb"
  - "app-editor/nano"
  - "app-editor/emacs"
